<?php
$title = 'Créer un mini cv étape '.($step +1) ;

$this->headTitle($title);
$this->headLink()->appendStylesheet($this->basePath('css/bootstrap-select.min.css'));
$this->headScript()->appendFile($this->basePath('js/bootstrap-select.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/adherents/continue.css'));

switch ($step) {
    case 2:
        $elements = [
            [
                'name' => 'contrat',
                'class' => 'form-control multicheck',
                'spe' => true,
            ],
            [
                'name' => 'dispo',
                'class' => 'selectpicker form-control'
            ],
            [
                'name' => 'mob',
                'class' => 'selectpicker form-control'
            ],
            [
                'name' => 'source',
                'class' => 'form-control'
            ],
        ];
        break;
    case 3:
        $elements = [];
        for ($i = 0; $i < $selector; $i++) {
            $elements[] = [
                'name' => 'comp'.$i,
                'class' => 'selectpicker form-control comp'
            ];
        }
        break;
    case 4:
        $elements = [];
        for ($i = 0; $i < $selector; $i++) {
            $elements[] = [
                'name' => 'compbis'.$i,
                'class' => 'selectpicker form-control compbis'
            ];
        }
        break;
    case 5:
    case 6:
        $elements = [];
        break;
    case 1:
    default:
        $elements = [
            [
                'name' => 'xp',
                'class' => 'form-control'
            ],
            [
                'name' => 'xptot',
                'class' => 'form-control'
            ],
            [
                'name' => 'formation',
                'class' => 'form-control'
            ],
        ];
        break;
}

foreach ($elements as $element) {
    $form->get($element['name'])->setAttributes([
        'class' => $element['class'],
    ]);
}
$form->prepare();
print_r($form->getMessages());
?>

<div class="row justify-content-center">
    <h1 class="mt-4 mb-5">
        <?= $title; ?>
    </h1>
</div>
<div class="row mt-5">
    <div class="col">
        <?= $this->form()->openTag($form); ?>
        <?php if ($step < 3): ?>
            <?php foreach ($elements as $element): ?>
                <?php $add = isset($element['spe']) ? "hiddenCB" : ""; ?>
                <div class="form-group <?= $add; ?>">
                    <?= $this->formLabel($form->get($element['name'])); ?>
                    <?= $this->formElement($form->get($element['name'])); ?>
                    <?= $this->formElementErrors($form->get($element['name'])); ?>
                </div>
            <?php endforeach; ?>
        <?php elseif ($step == 3): ?>
            <?= $this->FormHelper()->renderMetier(); ?>
        <?php elseif ($step == 4): ?>
            <?= $this->FormHelper()->renderMetier("compbis"); ?>
        <?php elseif ($step == 5): ?>
            <?= $this->FormHelper()->renderSecteur(); ?>
        <?php elseif ($step == 6): ?>
            <?= $this->FormHelper()->renderSe(); ?>
        <?php endif; ?>
        <div class="row mb-5">
        </div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
<?php
$this->inlineScript()->appendFile($this->basePath('js/adherents/continue.js'));
 ?>
