<?php
$title = 'Edition';

$this->headTitle($title);
$this->headLink()->appendStylesheet($this->basePath('css/bootstrap-select.min.css'));
$this->headScript()->appendFile($this->basePath('js/bootstrap-select.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/adherents/continue.css'));
switch ($part) {
    case 2:
        $elements = [
            [
                'name' => 'contrat',
                'class' => 'form-control multicheck',
                'spe' => true,
            ],
            [
                'name' => 'dispo',
                'value' => $minicv->getDispo()->getId(),
                'class' => 'selectpicker form-control'
            ],
            [
                'name' => 'mob',
                'value' => $minicv->getMobilite()->getId(),
                'class' => 'selectpicker form-control'
            ],
            [
                'name' => 'source',
                'value' => $minicv->getMobiliteSource(),
                'class' => 'form-control',
                'placeholder' => 'la Roche sur Yon'
            ],
        ];
        break;
    case 3:
        $elements = [];
        for ($i = 0; $i < $selector; $i++) {
            $elements[] = [
                'name' => 'comp'.$i,
                'class' => 'selectpicker form-control comp'
            ];
        }
        /*
        $value = [];
        foreach ($minicv->getComp() as $comp) {
            $value[] = $comp->getMetier()->getId();
        }
        */
        break;
    case 4:
        for ($i = 0; $i < $selector; $i++) {
            $elements[] = [
                'name' => 'compbis'.$i,
                'class' => 'selectpicker form-control compbis'
            ];
        }
        break;
    case 5:
    case 6:
        $elements = [];
        break;
    case 7:
        $elements = [
            [
                'name' => 'infos',
                'class' => 'form-control',
                'value' => $minicv->getInfosComp(),
                'placeholder' => 'Informations que vous souhaitez ajouter (facultatif)'
            ],
        ];
        break;
    case 1:
    default:
        $elements = [
            [
                'name' => 'xp',
                'class' => 'form-control',
                'placeholder' => '6 mois',
                'value' => $minicv->getExperiencePoste()
            ],
            [
                'name' => 'xptot',
                'class' => 'form-control',
                'value' => $minicv->getExperienceTotal(),
                'placeholder' => '10 ans'
            ],
            [
                'name' => 'formation',
                'value' => $minicv->getFormation(),
                'class' => 'form-control'
            ],
        ];
        break;
}

foreach ($elements as $element) {
    if(isset($element['placeholder'])) {
            $form->get($element['name'])->setAttributes([
                'placeholder' => $element['placeholder'],
            ]);
    }
    if(isset($element['value'])) {
        $form->get($element['name'])->setAttributes([
            'value' => $element['value'],
        ]);
    }
    $form->get($element['name'])->setAttributes([
        'class' => $element['class'],
    ]);
}
$form->prepare();
//print_r($form->getMessages());
?>
<div class="row justify-content-center">
    <h1 class="mt-4 mb-5">
        Edition de votre Minicv <?=$minicv->getIntitule() ?>
    </h1>
</div>
<div class="row mt-5">
    <div class="col">
        <?= $this->form()->openTag($form); ?>
        <?php if ($part < 3 || $part == 7): ?>
            <?php foreach ($elements as $element): ?>
                <?php $add = isset($element['spe']) ? "hiddenCB" : ""; ?>
                <div class="form-group <?= $add; ?>">
                    <?= $this->formLabel($form->get($element['name'])); ?>
                    <?= $this->formElement($form->get($element['name'])); ?>
                    <?= $this->formElementErrors($form->get($element['name'])); ?>
                </div>
            <?php endforeach; ?>
        <?php elseif ($part == 3): ?>
            <?= $this->FormHelper()->renderMetier("comp",$value); ?>
        <?php elseif ($part == 4): ?>
            <?= $this->FormHelper()->renderMetier("compbis"); ?>
        <?php elseif ($part == 5): ?>
            <?= $this->FormHelper()->renderSecteur(); ?>
        <?php elseif ($part == 6): ?>
            <?= $this->FormHelper()->renderSe(); ?>
        <?php endif; ?>
        <div class="row mb-5">
        </div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
<?php
$this->inlineScript()->appendFile($this->basePath('js/adherents/continue.js'));
 ?>
