<?php
$title = 'Créer un mini cv étape 1 sur 7';

$this->headTitle($title);
$this->headLink()->appendStylesheet($this->basePath('css/bootstrap-select.min.css'));
$this->headScript()->appendFile($this->basePath('js/bootstrap-select.min.js'));

$form->get('apec')->setAttributes([
    'class'=>'selectpicker form-control',
]);
$form->get('intitule')->setAttributes(array(
    'class'=> 'form-control',
    'placeholder' => 'intitulé de votre métier'
));
$form->prepare();

?>
<div class="row justify-content-center">
    <h1 class="mt-4 mb-5">
        <p><?= $title; ?></p>
        <p class="font-italic">Nature du métier</p>
    </h1>
</div>
<div class="row mt-5">
    <div class="col">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('apec')); ?>
            <?= $this->formElement($form->get('apec')); ?>
            <?= $this->formElementErrors($form->get('apec')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('intitule')); ?>
            <?= $this->formElement($form->get('intitule')); ?>
            <?= $this->formElementErrors($form->get('intitule')); ?>
        </div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
<?php
//$this->inlineScript()->appendFile($this->basePath('js/adherents/minicv.js'));
 ?>
