<?php
$title = 'Mini cv';

$this->headTitle($title);

?>
<div class="row justify-content-center">
    <h1 class="mt-4 mb-5">
        Votre Minicv <?=$minicv->getIntitule() ?>
    </h1>
</div>
<div class="row">
    <div< class="row">
    <?= $minicv->getApec()->getIntitule(); ?>
    </div>

    <div class="row mt-5">
        <div class="col">
            <ul>
                <p class="font-weight-bold text-success">
                    <a href="<?= $this->url('adherents', ['action' => 'edit','id' => $minicv->getId(),'part' => "1"])?>">
                        <img src="/img/edit.svg" alt="edit" width=25 height=25 />
                    </a>
                    Savoir-être :
                </p>
                <?php foreach ($minicv->getSavoirEtre() as $se): ?>
                    <li><?= $se->getNom(); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="col">
            <ul>
                <p class="font-weight-bold text-success">
                    <a href="<?= $this->url('adherents', ['action' => 'edit','id' => $minicv->getId(),'part' => "2"])?>">
                        <img src="/img/edit.svg" alt="edit" width=25 height=25 />
                    </a>
                    Compétences :
                </p>
                <?php foreach ($minicv->getComp() as $comp): ?>
                    <li><?= $comp->getNom(); ?></li>
                <?php endforeach; ?>
                <?php foreach ($minicv->getCompBis() as $comp): ?>
                    <li><?= $comp->getNom(); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col">
            <ul>
                <p class="font-weight-bold text-success">
                    <a href="<?= $this->url('adherents', ['action' => 'edit','id' => $minicv->getId(),'part' => "3"])?>">
                        <img src="/img/edit.svg" alt="edit" width=25 height=25 />
                    </a>
                    Secteurs ciblés :
                </p>
                <?php foreach ($minicv->getSecteur() as $secteur): ?>
                    <li><?= $secteur->getNom(); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="col">
            <ul>
                <p class="font-weight-bold text-success">
                    <a href="<?= $this->url('adherents', ['action' => 'edit','id' => $minicv->getId(),'part' => "4"])?>">
                        <img src="/img/edit.svg" alt="edit" width=25 height=25 />
                    </a>
                    Formations :
                </p>
                <li><?= nl2br($this->escapeHtml($minicv->getFormation())); ?></li>
            </ul>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col">
            <ul>
                <p class="font-weight-bold text-success">
                    <a href="<?= $this->url('adherents', ['action' => 'edit','id' => $minicv->getId(),'part' => "4"])?>">
                        <img src="/img/edit.svg" alt="edit" width=25 height=25 />
                    </a>
                    Disponibilité :
                </p>
                <li><?= $minicv->getDispo()->getDispo(); ?></li>
            </ul>
        </div>
        <div class="col">
            <ul>
                <p class="font-weight-bold text-success">
                    <a href="<?= $this->url('adherents', ['action' => 'edit','id' => $minicv->getId(),'part' => "5"])?>">
                        <img src="/img/edit.svg" alt="edit" width=25 height=25 />
                    </a>
                    Mobilité :
                </p>
                <li><?= $minicv->getMobilite()->getMobilite(); ?></li>
                <li>À partir de : <?= $minicv->getMobiliteSource(); ?></li>
            </ul>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col">
            <ul>
                <p class="font-weight-bold text-success">
                    <a href="<?= $this->url('adherents', ['action' => 'edit','id' => $minicv->getId(),'part' => "6"])?>">
                        <img src="/img/edit.svg" alt="edit" width=25 height=25 />
                    </a>
                    Expérience du poste :
                </p>
                <li><?= $this->escapeHtml($minicv->getExperiencePoste()); ?></li>
            </ul>
        </div>
        <div class="col">
            <ul>
                <p class="font-weight-bold text-success">
                    <a href="<?= $this->url('adherents', ['action' => 'edit','id' => $minicv->getId(),'part' => "7"])?>">
                        <img src="/img/edit.svg" alt="edit" width=25 height=25 />
                    </a>
                    Expérience totale:
                </p>
                <li><?= $this->escapeHtml($minicv->getExperienceTotal()) ?></li>
            </ul>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col">
            <ul>
                <p class="font-weight-bold text-success">
                    <a href="<?= $this->url('adherents', ['action' => 'edit','id' => $minicv->getId(),'part' => "8"])?>">
                        <img src="/img/edit.svg" alt="edit" width=25 height=25 />
                    </a>
                    Informations complémentaires:
                </p>
                <li><?= $this->escapeHtml($minicv->getInfosComp()) ?></li>
            </ul>
        </div>
    </div>
</div>
<?php
$this->inlineScript()->appendFile($this->basePath('js/adherents/upload.js'));
 ?>
