<?php
$title = 'panel admin';

$this->headTitle($title);
?>

<div class="row">
    <div class="col mx-auto">
        <h1 class="text-center">Panneau d'administration</h1>
    </div>
</div>
<div class="row">
    <div class="col-6">
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'users']); ?>">
                    <button type="button" class="btn btn-success">Gérer les utilisateurs</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'apec']); ?>">
                    <button type="button" class="btn btn-success">Gérer Apec</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'metier']); ?>">
                    <button type="button" class="btn btn-success">Gérer les métiers</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'comp']); ?>">
                    <button type="button" class="btn btn-success">Gérer les compétences</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'compbis']); ?>">
                    <button type="button" class="btn btn-success">Gérer les compétences complémentaires</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'secteur']); ?>">
                    <button type="button" class="btn btn-success">Gérer les secteurs</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'savoiretrecat']); ?>">
                    <button type="button" class="btn btn-success">Gérer les catégories de savoirs êtres</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'savoiretre']); ?>">
                    <button type="button" class="btn btn-success">Gérer les savoirs êtres</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'contrat']); ?>">
                    <button type="button" class="btn btn-success">Gérer les types de contrat</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'dispo']); ?>">
                    <button type="button" class="btn btn-success">Gérer les disponibilité</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'mob']); ?>">
                    <button type="button" class="btn btn-success">Gérer les mobilité</button>
                </a>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'mvc']); ?>">
                    <button type="button" class="btn btn-info">Gérer les minis cv</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'log']); ?>">
                    <button type="button" class="btn btn-info">Voir les journaux</button>
                </a>
            </div>
        </div>
    </div>
</div>
