<?php
$title = 'panel admin';

$this->headTitle($title);
$this->headScript()->appendFile($this->basePath('js/Chart.bundle.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/Chart.min.css'));
?>

<div class="row">
    <div class="col mx-auto">
        <h1 class="text-center">Panneau d'administration</h1>
    </div>
</div>
<div class="row">
    <div class="col-6">
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'users']); ?>">
                    <button type="button" class="btn btn-success">Gérer les utilisateurs</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'apec']); ?>">
                    <button type="button" class="btn btn-success">Gérer Apec</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'metier']); ?>">
                    <button type="button" class="btn btn-success">Gérer les métiers</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'comp']); ?>">
                    <button type="button" class="btn btn-success">Gérer les compétences</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'compbis']); ?>">
                    <button type="button" class="btn btn-success">Gérer les compétences complémentaires</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'secteur']); ?>">
                    <button type="button" class="btn btn-success">Gérer les secteurs</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'savoiretrecat']); ?>">
                    <button type="button" class="btn btn-success">Gérer les catégories de savoir être</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'savoiretre']); ?>">
                    <button type="button" class="btn btn-success">Gérer les savoir être</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'contrat']); ?>">
                    <button type="button" class="btn btn-success">Gérer les types de contrat</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'dispo']); ?>">
                    <button type="button" class="btn btn-success">Gérer les disponibilités</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'mob']); ?>">
                    <button type="button" class="btn btn-success">Gérer les mobilités</button>
                </a>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'mcv']); ?>">
                    <button type="button" class="btn btn-info">Gérer les minis cv</button>
                </a>
            </div>
        </div>
        <div class="row my-3">
            <div class="col">
                <a href="<?= $this->url('admin', ['action' => 'log']); ?>">
                    <button type="button" class="btn btn-info">Voir les journaux</button>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
        <div class="col-5">
                <canvas id="myChart" width="200" height="200"></canvas>
        </div>
</div>

<?php
$intitule  = [];
$value = [];
foreach ($apec as $a) {
    if ($a->getMinicv()->count() > 0) {
        $intitule[] = $a->getIntitule();
        $value[] = $a->getMinicv()->count();
    }
}
print_r($intitule);
print_r($value);
?>
<script>

var config = {
    type: 'pie',
    data: {
        datasets: [{
            data: [
                <?php
                foreach ($value as $val) {
                    echo $val.",";
                }
                ?>
            ],
            backgroundColor: [
                'red',
                'orange',
                'yellow',
                'green',
                'blue',
            ],
        }],
        labels: [
            <?php
            foreach ($intitule as $name) {
                echo "'".$name."',";
            }
            ?>
        ]
    },
    options: {
        responsive: true
    }
};
var ctx = document.getElementById('myChart').getContext('2d');
var myPieChart = new Chart(ctx,config);


</script>
