<?php
$title = 'Cv en attente de validation';

$this->headTitle($title);
$this->headLink()->appendStylesheet($this->basePath('css/adherents/upload.css'));

?>
<div class="row justify-content-center">
    <h1 class="mt-4 mb-5">
        <?= $title; ?>
    </h1>
</div>
<div class="row mb-5">
    <?php foreach ($minicvs as $minicv):
        if ($minicv->getValid()) {
            $mcvPriv = "";
            $mcvPub = "checked";
        } else {
            $mcvPriv = "checked";
            $mcvPub = "";
        }
        ?>
        <div class="col">
             <a href="<?= $this->url('adherents', ['action' => 'view','id' => $minicv->getId()])?>">Voir <?= $minicv->getIntitule() ?></a>
        </div>
        <div class="col">
            <span class="group">
            <input type="radio" class="change" name="state<?= $minicv->getId(); ?>" id="u<?= $minicv->getId(); ?>" <?= $mcvPriv; ?>>
            <label for="u<?= $minicv->getId(); ?>">En attente</label>
            <input type="radio" class="change" name="state<?= $minicv->getId(); ?>" id="p<?= $minicv->getId(); ?>" <?= $mcvPub; ?>>
            <label for="p<?= $minicv->getId(); ?>">Valide</label>
            </span>
        </div>
    <?php endforeach; ?>
</div>
<?php
$this->inlineScript()->appendFile($this->basePath('js/admin/mcv.js'));
 ?>
