<?php
$title = 'Gestion Mobilité';

$this->headTitle($title);
$this->headLink()->appendStylesheet($this->basePath('css/admin/admin.css'));
$form->get('submit')->setAttributes(['class'=>'btn btn-lg btn-primary btn-block']);

$form->get('mob')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Nouvelle mobilité'
]);
$form->prepare();
//print_r($form->getMessages());

?>
<div class="row justify-content-center">
    <h1 class="mt-4 mb-5">
        <?= $title; ?>
    </h1>
</div>

<div class="row mt-5">
    <div class="col-sm-6">
        <?= $this->AdminRender()->renderMob(); ?>
    </div>
    <div class="col-sm-6">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('mob')); ?>
            <?= $this->formElement($form->get('mob')); ?>
            <?= $this->formElementErrors($form->get('mob')); ?>
        </div>
        <?= $this->formElement($form->get('csrf')) ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
        <button id="delete" type="button" class="btn mt-3 btn-danger btn-lg btn-block">Suprimer le.s mobilité.s</button>
    </div>
</div>

<?php
$this->inlineScript()->appendFile($this->basePath('js/admin/mob.js'));
 ?>
