<?php
$title = 'Gestion Secteur';

$this->headTitle($title);
$this->headLink()->appendStylesheet($this->basePath('css/bootstrap-select.min.css'));
$this->headScript()->appendFile($this->basePath('js/bootstrap-select.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/admin/admin.css'));

$form->get('submit')->setAttributes(['class'=>'btn btn-lg btn-primary btn-block']);

$form->get('nom')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Nouveau secteur'
]);
$form->get('type')->setAttributes(array(
    'class'=> 'selectpicker',
));
$form->prepare();
//print_r($form->getMessages());

?>
<div class="row justify-content-center">
    <h1 class="mt-4 mb-5">
        <?= $title; ?>
    </h1>
</div>

<div class="row mt-5">
    <div class="col-sm-6">
        <?= $this->AdminRender()->renderSecteur(); ?>
    </div>
    <div class="col-sm-6">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('nom')); ?>
            <?= $this->formElement($form->get('nom')); ?>
            <?= $this->formElementErrors($form->get('nom')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('type')); ?>
            <?= $this->formElement($form->get('type')); ?>
            <?= $this->formElementErrors($form->get('type')); ?>
        </div>
        <?= $this->formElement($form->get('csrf')) ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
        <button id="delete" type="button" class="btn mt-3 btn-danger btn-lg btn-block">Suprimer le.s secteur.s</button>
    </div>
</div>

<?php
$this->inlineScript()->appendFile($this->basePath('js/admin/secteur.js'));
 ?>
