<style type="text/css">
p {
    color: green;
}
.title {
    color: red;
}
.tg  {border-collapse:collapse;border-color:black;border-spacing:0;border-style:solid;border-width:1px;margin:0px;}
.tg td{border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;
  padding:10px 5px;word-break:normal;}
.tg th{border-style:solid;border-width:0px;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0lax{text-align:left;vertical-align:top}
.tg .tg-tf2e{text-align:left;vertical-align:top}
@media screen and (max-width: 767px) {.tg {width: auto !important;}.tg col {width: auto !important;}.tg-wrap {overflow-x: auto;-webkit-overflow-scrolling: touch;margin: auto 0px;}}
</style>
<?php
if($apec === NULL) {
    echo("error");
    exit(1);
}
?>

<h2><?= $apec->getIntitule(); ?></h2>


<?php foreach ($apec->getMinicv() as $minicv): ?>
<?php
    //check if profile is valid and public
    if($minicv->getPublish() != 1 or $minicv->getValid() != 1)
        continue;
?>

<div class="tg-wrap">
    <span class="title"><?=$minicv->getIntitule() ?></span> :
    <table class="tg">
        <tbody>
          <tr>
            <td class="tg-0lax">
                <p>
                    Savoir-être
                </p>
                <?php foreach ($minicv->getSavoirEtre() as $se): ?>
                    <li><?= $se->getNom(); ?></li>
                <?php endforeach; ?>
            </td>
            <td class="tg-0lax">
                <p>Compétences</p>
                <?php foreach ($minicv->getComp() as $comp): ?>
                    <li><?= $comp->getNom(); ?></li>
                <?php endforeach; ?>
                <?php foreach ($minicv->getCompBis() as $comp): ?>
                    <li><?= $comp->getNom(); ?></li>
                <?php endforeach; ?>
            </td>
          </tr>
          <tr>
            <td class="tg-tf2e">
                <p>Secteurs ciblés</p>
                <?php foreach ($minicv->getSecteur() as $secteur): ?>
                    <li><?= $secteur->getNom(); ?></li>
                <?php endforeach; ?></td>
            <td class="tg-tf2e"><p>Formations</p>
                <?= nl2br($this->escapeHtml($minicv->getFormation())); ?>
            </td>
          </tr>
          <tr>
            <td class="tg-0lax"><p>Disponibilité</p> <li><?= $minicv->getDispo()->getDispo(); ?></li> </td>
            <td class="tg-0lax"><p>Mobilité</p>
                <li><?= $minicv->getMobilite()->getMobilite(); ?></li>
                <li>À partir de : <?= $minicv->getMobiliteSource(); ?></li>
            </td>
          </tr>
          <tr>
            <td class="tg-tf2e"><p>Expérience du poste</p>
                <li><?= $this->escapeHtml($minicv->getExperiencePoste()); ?></li>
            </td>
            <td class="tg-tf2e"><p>Expérience totale</p>
                <li><?= $this->escapeHtml($minicv->getExperienceTotal()) ?></li>
            </td>
          </tr>
          <tr>
            <td class="tg-0lax"><p>Contrat recherché</p>
                <?php foreach ($minicv->getContrat() as $contrat): ?>
                    <li><?= $contrat->getType(); ?></li>
                <?php endforeach; ?>
            </td>
            <td class="tg-0lax"><p>Information complémentaires</p>
                <?= $this->escapeHtml($minicv->getInfosComp()) ?>
            </td>
          </tr>
        </tbody>
    </table>
    <?php
    if($minicv->getUser()->getUpload()->count() > 0  and $minicv->getUser()->getUpload()->first()->getPublic() == 1): ?>
         <a href="<?= "https://adherents.vendeecadres.com/cv/".$minicv->getUser()->getUpload()->first()->getFile(); ?>">Télécharger Le CV associé</a>
    <?php endif; ?>
    <button id="<?=$minicv->getId(); ?>" type="button">Ce profil m'intéresse</button>
</div>
<br />
<?php endforeach; ?>
<form class="modal" id="modal" style="display:none;">
  <h3>Veuillez laisser vos coordonnées</h3>
  <p><label>Nom - Prénom </label> <input id="name" type="text" placeholder="Dupont Jean" required></p>
  <p><label>email : </label> <input type="email" id="email" name="email" placeholder="dupont.j@example.com" required></p>
  <p><label>Message : </label><textarea id="message" rows="4" cols="50">Bonjour, votre profil m'intéresse merci de me contacter !</textarea></p>
  <input type="hidden" id="minicv" name="minicv" value="">
  <p><input id="send" type="submit" value="Envoyer" /></p>
</form>
<div class="modal" id="sucess" style="display:none;">
  <p>Votre message vient d'être envoyé</p>
</div>
<script>
$(function(){
    $('button').click(function(){
        $("#minicv").val($(this).attr('id'));
        $("#modal").modal();
    });
    $("#modal").submit(function(e){
        //retreive data
        e.preventDefault();
        var name  = $("#name").val();
        var email = $("#email").val();
        var msg   = $("#message").val();
        var id    = $("#minicv").val();
        console.log("Current id" + id)
        return
        console.log(name);
        console.log(email);
        console.log(msg);
        console.log(id);
        $.ajax({
           type: 'POST',
           url: 'profils/msg',
           data: { name : name, id: id, msg: msg,email : email } ,
           dataType: 'json',
           success: function (data) {
                if(data.SUCCES == "OK") {
                    console.log("mesage envoyé");
                    $("#sucess").modal();
                } else {
                    console.log("erreur");
                    $.modal.close();
                }
           }
       });
    });
});
</script>
