<?php
$intitule  = [];
$value = [];
foreach ($apec as $a) {
    if ($a->getMinicv()->count() > 0) {
        $cpt = 0;
        $intitule[] = $a->getIntitule();
        foreach ($a->getMinicv() as $minicv) {
            if($minicv->getPublish() == 1 and $minicv->getValid() == 1)
                $cpt++;
        }
        $value[] = $cpt;
    }
}
?>
<html>
<head>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
</head>
<body>
<div id="retour">
    <a href="javascript:;">Retour aux catégories</a>
</div>
<div id="myGraph">
    <canvas id="myChart" width="200" height="200"></canvas>
</div>

<div id="myData">

</div>
<script>
$(function(){

$("#retour").hide();
$("#myGraph").show();
$("#myData").empty();

$("#retour").click(function(){
    $("#retour").hide();
    $("#myGraph").show();
    $("#myData").empty();
    $("#modal").remove();
});

function pullCat(id) {
    $("#myGraph").hide();
    $.ajax({ type: "POST",
        url: "profils/data",
        data: { cat : id},
        dataType: "html",
        success: function(html){
            $("#myData").empty();
            $("#myData").append(html);
            $("#retour").show();
            $("#myData").show();
          console.log("success : " + id)
        }
    });
}

function displayCat(cat) {
    console.log(cat)
    switch (cat) {
        case "Médical, social":
            pullCat(30);
            break;
        case "Direction":
            pullCat(19);
            break;
        case "Production, chantiers":
            pullCat(20);
            break;
        case "Services techniques":
            pullCat(23);
            break;
        case "Études, R&D, architecture":
            pullCat(24);
            break;
        case "Commercial, marketing, ventes, immobilier":
            pullCat(25);
            break;
        case "Administration, compta, finances, gestion":
            pullCat(26);
            break;
        case "Informatique, télécoms":
            pullCat(27);
            break;
        case "RH, formation":
            pullCat(28);
            break;
        case "Communication, création, culture":
            pullCat(29);
            break;
        case "Médical, social":
            pullCat(30);
            break;
        default:
            console.log("undef cat");
            return;
    }
}

var config = {
    type: 'doughnut',
    data: {
        datasets: [{
            data: [
                <?php
                foreach ($value as $val) {
                    echo $val.",";
                }
                ?>
            ],
            backgroundColor: [
                'red',
                'orange',
                'gold',
                'yellow',
                'SpringGreen',
                'green',
                'Aquamarine',
                'blue',
                'MediumVioletRed',
                'Purple',
            ],
        }],
        labels: [
            <?php
            foreach ($intitule as $name) {
                echo "'".$name."',";
            }
            ?>
        ]
    },
    options: {
        responsive: true
    }
};
var ctx = document.getElementById('myChart');
var myPieChart = new Chart(ctx,config);

ctx.onclick = function(evt) {
      var activePoints = myPieChart.getElementsAtEvent(evt);
      if (activePoints[0]) {
        var chartData = activePoints[0]['_chart'].config.data;
        var idx = activePoints[0]['_index'];

        var label = chartData.labels[idx];
        var value = chartData.datasets[0].data[idx];
        displayCat(label)
        console.log(label);
      }
    };
});
</script>
</body>
</html>
